### ISSUE TITLE
what is the result of this project

### ISSUE THREAD

**Issue by StoneClose** [mbaytas/HoloLensUDP#1]
What is the final result?Change the unity text, and HoloLens displays it?
why i deploy it to hololens  ,and change the text in the unity ,but the hololens still dissplay the first word?
when i build setting  the project .the unity display that "unable to access unity services ,please log in ,or request membership to this project to use this servicrs"?

**Comment by mbaytas** [comment]
There is a public TextMesh property on the UDPResponse script, which has to be pointed to a TextMesh in the scene. The script listens to incoming UDP messages and prints them to the TextMesh.

See: https://github.com/mbaytas/HoloLensUDP/blob/master/Assets/Scripts/UDPResponse.cs

That said, I have not been maintaining this already somewhat precarious project for more than a year now. It may have been broken by recent updates to Unity or the HoloLens dev tools.

**Comment by mbaytas** [comment]
There is a public TextMesh property on the UDPResponse script, which has to be pointed to a TextMesh in the scene. The script listens to incoming UDP messages and prints them to the TextMesh.

See: https://github.com/mbaytas/HoloLensUDP/blob/master/Assets/Scripts/UDPResponse.cs

That said, I have not been maintaining this already somewhat precarious project for more than a year now. It may have been broken by recent updates to Unity or the HoloLens dev tools.
